version: "3.3"
services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
    restart: always
  db:
    build: ./requirements/mariadb/
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    build: ./requirements/wordpress/
    ports:
      - "9000:9000"
    restart: always
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
    container_name: 'wordpress'
