version: "3.3"
services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    ports:
      - "443:443"
    restart: always
    volumes:
      - wp:/var/www/html/.
    networks:
      - default

  mysql:
    build: ./requirements/mysql/
    expose:
      - "3306"
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default

  wordpress:
    depends_on:
      - mysql
    build: ./requirements/wordpress/
    expose:
      - "9000"
    volumes:
      - wp:/var/www/html/.
    restart: always
    environment:
       WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
       WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
       WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
       WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - default
    container_name: 'wordpress'

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/hyeolee/volume_test/db'

  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/hyeolee/volume_test/wp'

networks:
  default:
    driver: bridge