ALTER USER 'root'@'localhost' IDENTIFIED BY '1111';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS wordpress;
GRANT ALL PRIVILEGES ON *.* TO 'wordpress'@'%' IDENTIFIED BY 'wordpress' WITH GRANT OPTION;
FLUSH PRIVILEGES;
